### ISSUE TITLE
Migrate dashbaords to influxdb

### ISSUE THREAD

**Issue by coryschwartz** [testground/testground#1014]
Configure the dashboards to use influxdb rather than prometheus as the datasource. This is part of the migration to influx.

Can do this while doing the documentation on https://github.com/testground/testground/issues/765

**Comment by nonsense** [comment]
@coryschwartz I am not sure what this issue is about. We are currently using:
1. prometheus for infra monitoring
2. influxdb for app/testplan monitoring

We should have both `datasources` automatically provisioned on all environments (I think we already do that on `cluster:k8s`, but not on `local:docker` and `local:exec`.

Then dashboards should use the correct `datasource` they apply to:
1. Currently all auto-provisioned dashboards are using `prometheus`, because they are infra related.
2. Test plan dashboards (such as the one in https://github.com/testground/testground/pull/877) should reference `influxdb`.

**Comment by coryschwartz** [comment]
@nonsense ^^ just to deal with these prometheus dashboards. Closing now with that merged.
