### ISSUE TITLE
`testground run single help` describes default value for instances, but fails without

### ISSUE THREAD

**Issue by jfietz** [testground/testground#1070]
## Description

`$ testground run single help
[...]
   --instances value, -i value     number of instances of the test case to run (default: 0)
[...]`

The explanation here talks about a default value (0), but fails by showing the complete help and `Required flag "instances" not set`.
## What defines this endeavour to be complete?

Either remove the requirement or fix the docs. 

Right now, it's possible to set default values for the number of instances in the manifest as well. This seems contradictory with requiring this on the command line.

**Comment by raulk** [comment]
The number of instances is actually compulsory, IIRC.

We used to support default instance counts, but we decided to remove that magic in favour of usability and explicitness. We no longer parse it out of the manifest: https://github.com/testground/testground/blob/1f4297117c2c25fbe8ccf1e42a8b57a22afa445f/pkg/api/manifest.go#L38-L41

We should fix the CLI so that it doesn't trick you into thinking there's a default applied. I think this is an artifact of go's zero values.

**Comment by jfietz** [comment]
As a minor add-on then, I only got the idea about default values in the manifest from the automatically generated manifest in quickstart, as well as some of the example files, e.g.:

```
https://github.com/testground/testground/blob/master/plans/example/manifest.toml
https://github.com/testground/testground/blob/master/plans/benchmarks/manifest.toml
```

as well as the autogenerated toml file. 

PS: I wish I could decrease the importance of this to zero, but figured I'd report ;)
