### ISSUE TITLE
rethink the rolling docker:go cache build

### ISSUE THREAD

**Issue by nonsense** [testground/testground#1088]
Currently if we set `enable_go_build_cache = true` build config for docker:go builder, we do a rolling build cache using `func (b *DockerGoBuilder) parseBuildCacheOutputImage(output string) string {`which looks for an intermediate image ID, and caches it, so that we don't have to rebuild Go source-code multiple times.

However overlay2 storage driver has a max depth of 125 layers, and by selecting an intermediate image ID, we can't really use the docker build `--squash` option.

We have to come up with a way to squash the cache image, so that we stop hitting the 125 layers limit.

**Comment by nonsense** [comment]
Since I can't find an available API for squashing images, one thing we could try is:

```
$ docker run -d gocacheimage /bin/true
c101557c0b9b7139a3b897273dbe294ac02ce83139a7013dff06c0c470cb2b93
$ docker export c101 | docker import - gocacheimage
```

**Comment by nonsense** [comment]
My comment above is not actually going to work, because we use a `cursor` to detect an intermediate image.

One solution would be to introduce a flag or two so that we build a cached image on-demand once and then just use the initial image. If the up-to-date image changes too much from the underlying cache, it should be easy to clear and rebuild the cached image again. Currently we are doing a rolling cache on every build, but that quickly hits the number of layers an image can have.

**Comment by hacdias** [comment]
@nonsense Let me see if I understand: right now, enabling the Go build cache, makes Testground parse the output of the build (after the build of course) and pick the last ID from the `AS builder` image. Then, we cache the image.

The problem is that the overlay2 driver can only have 125 layers and if we end up with more than that, the build doesn't work. To fix that, we need to collapse everything into only one layer. But using an intermediate ID, the `--squash` thing doesn't work and we need to come up with an idea for that.

The idea you're suggesting is:

1. If there is some flag
	1. Pick up a similar version to `DockerfileTemplate` that ends just before the runtime part.
	2. Build it and squash it.
	3. Pick up the final ID and use it on the build afterwards as the base image.
2. If not, just do as usual.

Is that right?

**Comment by nonsense** [comment]
> @nonsense Let me see if I understand: right now, enabling the Go build cache, makes Testground parse the output of the build (after the build of course) and pick the last ID from the AS builder image. Then, we cache the image.
> The problem is that the overlay2 driver can only have 125 layers and if we end up with more than that, the build doesn't work. To fix that, we need to collapse everything into only one layer. But using an intermediate ID, the --squash thing doesn't work and we need to come up with an idea for that.

Yes, that's right.

---

The main problem is that if you do a number of builds (for example 9-10 builds), you accumulate all the layers from all the intermediate caches, and the number of layers keeps on growing.

What I am suggesting is the following: usually when you work on a test plan it doesn't change so often from one build to the next, so caching it only once will have the same effect as what we are doing now - the rolling cache.

Therefore we get similar speed benefit if we have functionality that allows us to:
- do a cache once (similar to what we do now) and then
- use that cache for subsequent builds without keep on adding a new cache on top of it

We would then need an easy way, part of Testground, to clear the cache (so that we can re-create one from scratch in case the build diverged a lot over the course of hours/days of development). At the moment we do that with `docker rmi tg-gobuildcache-lotus-soup` (where `lotus-soup` is a test plan name).

Any other ideas are also welcome!

**Comment by hacdias** [comment]
My idea to implement this is as follows:

- If the cache is enabled, then create an image with the build dependencies and use the squash option. On subsequent builds, use that image as the base. This might increase the first build time because we will be building two images instead of one. However, this allows us to bypass the 125 layers limit of the storage driver.
- Add a command to cleanup the cache per plan.

Will start implementing this to see if I can get tangible improvements. @nonsense what do you think?

**Comment by hacdias** [comment]
Update: https://github.com/testground/testground/pull/1115

**Comment by hacdias** [comment]
We ended up removing the "rolling" mechanism by just building the cache once. Now the developer must choose when to clear up the cache. For more details, read [this comment](https://github.com/testground/testground/pull/1115#issue-456738671).
