### ISSUE TITLE
network ping-pong Step 13/22 : RUN echo "Using go proxy: ${GO_PROXY}"     && cd ${PLAN_DIR}     && go env -w GOPROXY="${GO_PROXY}"     && go mod download  ---> Running in 25f0067cd096 Using go proxy: http://testground-goproxy:8081

### ISSUE THREAD

**Issue by 279358738** [testground/testground#1185]
Step 13/22 : RUN echo "Using go proxy: ${GO_PROXY}"     && cd ${PLAN_DIR}     && go env -w GOPROXY="${GO_PROXY}"     && go mod download
 ---> Running in 25f0067cd096
Using go proxy: http://testground-goproxy:8081
go: github.com/kr/text@v0.2.0/go.mod: verifying module: github.com/kr/text@v0.2.0/go.mod: Get "https://sum.golang.org/lookup/github.com/kr/text@v0.2.0": dial tcp 172.217.160.81:443: i/o timeout
Jan  5 08:40:27.735330	INFO	build failed	{"plan": "network", "groups": ["single"], "builder": "docker:go", "error": "docker build failed: The command '/bin/sh -c echo \"Using go proxy: ${GO_PROXY}\"     && cd ${PLAN_DIR}     && go env -w GOPROXY=\"${GO_PROXY}\"     && go mod download' returned a non-zero code: 1"}
Jan  5 08:40:27.735412	ERROR	doRun returned err	{"err": "docker build failed: The command '/bin/sh -c echo \"Using go proxy: ${GO_PROXY}\"     && cd ${PLAN_DIR}     && go env -w GOPROXY=\"${GO_PROXY}\"     && go mod download' returned a non-zero code: 1"}

PS: I am in china

**Comment by nonsense** [comment]
@279358738 the error message is part of the output - the build failed because: `go: github.com/kr/text@v0.2.0/go.mod: verifying module: github.com/kr/text@v0.2.0/go.mod: Get "https://sum.golang.org/lookup/github.com/kr/text@v0.2.0": dial tcp 172.217.160.81:443: i/o timeout`

goproxy failed to download a dependency of the project you are trying to build.

This could be either a temporary error (so try again), or this dependency might not be reachable from your end (I can open it from here - https://github.com/kr/text/releases/tag/v0.2.0)

**Comment by nonsense** [comment]
@279358738 let me know if you have any other problems, but this appears to be a user issue, and not a problem with Testground.
