### ISSUE TITLE
Rampup Bloxico 2022Q1

### ISSUE THREAD

**Issue by BigLep** [testground/testground#1288]
This is meant to capture the information that PL EngRes needs to provide or steps they need to take to effectively rampup Bloxico as part of https://github.com/filecoin-project/devgrants/issues/440

Please add anything to the list you think of...

Access related:
- [x]  @biglep create a testground/bloxico team with high permissions to the repos: https://github.com/orgs/testground/teams/bloxico
- [x]  @biglep to create a GitHub project board can use for sequencing work: https://github.com/orgs/testground/projects/2/
- [x]  More covered in https://github.com/testground/testground/issues/1289

Prereqs before doing architectural deep dive
- [x] https://github.com/testground/testground/issues/1291
- [ ] https://github.com/testground/testground/issues/1290
- [x] https://github.com/testground/docs/blob/master/misc/presentations/k8s-networkings.slide (it's made to be presented with https://pkg.go.dev/golang.org/x/tools/present )
 - This is a presentation on Testground from January, 2020 which includes the requirements for the Testground networking, and why we picked Weave/Flannel

This issue will get marked done when the architecture deep dive has occurred.  
@brdji will schedule this meeting once it's clearer when those involved will have done the prereqs.

**Comment by BigLep** [comment]
@brdji feel free to edit and anything else that you know that you need as it comes up.

**Comment by galargh** [comment]
@BigLep I set up GitHub Management for `testground` here: https://github.com/testground/github-mgmt

I used it to propose creation of `bloxico` team with `maintain` access to all the other repos - https://github.com/testground/github-mgmt/pull/2. The next step will be to determine who the team members should be.

I also created a GitHub Project - https://github.com/orgs/testground/projects/1 - and populated it with all the open issues from `testground` org (feel free to delete if you want to do it differently).

**Comment by galargh** [comment]
> Please add me to the bloxico team, and I can add the rest of the members (if such permissions are available).

Created a PR for this - I'll wait for Steve to approve. 

As for empowering you to add others, we have a couple of options (they'll make more sense once you become an org member and can see https://github.com/testground/github-mgmt 😄):
1. You can add others to the organisation and to the `bloxico` team. You'll be able to do that by making a PR with a changeset like this https://github.com/testground/github-mgmt/commit/c88fd9749795ee089d23c021778ac06434d57461 to https://github.com/testground/github-mgmt. 
1. You can add others to specific repositories as external contributors. You'll be able to do that by making a PR with a changeset like this https://github.com/testground/github-mgmt/commit/40d06f5f048fe50e01eae0cfbae22eb43871a45b to https://github.com/testground/github-mgmt.

Both of these options will be possible since I enabled creating forks of private repos in this organisation.

**Comment by BigLep** [comment]
Thanks @galargh for all this!

I responded don't he PR.

I also created a new board: https://github.com/orgs/testground/projects/2/views/1 .  I want to make sure that we are disciplined about what we put on the board so it doesn't get cluttered (opt in vs opt out).

Good stuff!

**Comment by galargh** [comment]
@brdji FYI you should have an invitation to testground org waiting for you in your inbox.

**Comment by BigLep** [comment]
Architecture deep dive recording: https://anton-public-bucket-boost.s3.eu-central-1.amazonaws.com/GMT20220324-130824_Recording_1920x1050.mp4

**Comment by KatarinaKeti** [comment]
Should we close this issue?

**Comment by galargh** [comment]
> Should we close this issue?

Yeah, I think we can consider the "rampup" to be complete. I'll remove https://github.com/testground/testground/issues/1288#issuecomment-1130198195 from prerequisites here since it feels like a separate issue.
