### ISSUE TITLE
Investigate cluster infrastructure

### ISSUE THREAD

**Issue by KatarinaKeti** [testground/testground#1310]

**Comment by AbominableSnowman730** [comment]
We've gone through the process of inspecting the state of the current infrastructure. [The public Testgound infra repository](https://github.com/testground/infra/) (even tho it's outdated) holds all of the code necessary to bootstrap all the things necessary to spin up a k8s cluster. 
_Note:_ A few changes had to be made so that the provided scripts could be able to provision a k8s successfully. This has been documented in [the working document](https://docs.google.com/document/d/1k64pkxy8Sd4oCP9mz97556LdOcozlpAnewmFwQM_XuY). The document will remain privately visible until we determine whether the migration to a hosted k8s cluster is possible. 
_Note 2_: There's a couple of additional steps that are required so the cluster can be externally accessible through a fqdn. This configuration is company-specific, and it should not be included in the public repository (although we might want to include additional details in the documentation).
