### ISSUE TITLE
Write down documentation changes

### ISSUE THREAD

**Issue by KatarinaKeti** [testground/testground#1311]

**Comment by AbominableSnowman730** [comment]
Documentation changes were noted in [the following document](https://docs.google.com/document/d/1k64pkxy8Sd4oCP9mz97556LdOcozlpAnewmFwQM_XuY). 
_Note_: Contents within will remain visible only to the team that's working on it, since we still have no clear picture whether we will be able to perform migration to a hosted cloud solution. If that's the case, the current state of the documentation will become obsolete. If the migration is not feasible, we will reference the document's contents to guide us through the process of improving the current state of affairs.
