### ISSUE TITLE
Phase 2 Progress Report

### ISSUE THREAD

**Issue by brdji** [testground/testground#1439]
Please find the phase 2 progress report in the attached file.

[Phase 2 report.pdf](https://github.com/testground/testground/files/9495535/Phase.2.report.pdf)

**Comment by BigLep** [comment]
@brdji and @KatarinaKeti : I'm confused by this.  It seems premature to be claiming a completion report.  I don't think we've completed the "phase".  Examples:
1. The milestone itself has many open issues: https://github.com/testground/testground/milestone/17
2. Nothing has been completed that is making an engineering team's life better (e.g., PL EngRes libp2p, Ethereum implementation team).  There isn't the ability for a developer to spin up an autoscaling cluster that they can run testplans against and there isn't a working TaaS either.
3. There are various things in the "phase" that aren't relevant anymore:
 - Add rust support: PL EngRes took this on
 - Fix and maintain JS support: I asked that this not be engaged with until we deliver on the cluster items.

I'm assuming there's a disconnect.  What prompted Bloxico to believe it was time for a completion report?  Is it because of the schedule set in the original "Open Source Software Grant Agreement"?

I'm worried here that we spent time documenting something as complete when it wasn't, when a more effective mechanism would be to have a clearly defined GitHub milestone with well defined issues in the milestone.  I think that would have taken less work, been more clear, and yielded better results.

There are things in the report that myself or others could leave comments on.  I'm not going to do that currently to stay focused on the bigger picture that I don't think we should be claiming the phase complete.  If you would like feedback on the report itself, myself or someone else on the team can provide it.

Also, I see that phase 1 items are also not complete: https://github.com/testground/testground/milestone/16

**Comment by brdji** [comment]
@BigLep 
We have posted the phase 2 report as required by the schedule. I agree that the term “completion” is incorrect in this case, and have reworded the issue and report to reflect this. You are correct that we have fallen behind schedule (as can be seen in the report), and have not yet deployed any meaningful improvements that we have planned to do by the end of the phase (ie. deploying the TaaS cluster). 

Rust and JS support: as outlined in the proposal, we spent a bit of time investigating the JS and Rust support in July. Having found that both were working (and having consulted with PL’s Rust team), no further effort was spent on these issues.

> Also, I see that phase 1 items are also not complete: https://github.com/testground/testground/milestone/16

The items from phase 1 are considered "ongoing" as we continue to benchmark and fix the networking issues with the cluster.  I see now that we haven't made that clear in the issues' description and haven't updated them in a while. However, as we have almost completed our investigation into the EKS cluster options, we will prepare a short report on the current cluster performance, scaling, benchmark tests, and findings, link to the report, and close the issues.
Two issues were erroneously added to the milestone (IPv6 and browser test support, added on the 18th of July), when they should have been simply added to the backlog instead. We have removed these issues from the milestone.

> I'm worried here that we spent time documenting something as complete when it wasn't, when a more effective mechanism would be to have a clearly defined GitHub milestone with well defined issues in the milestone. I think that would have taken less work, been more clear, and yielded better results.

Agreed. We will have an internal discussion and will schedule a call with you as soon as possible, so we can rework how we handle tasks, and preferably move to a more agile process.

As always, we welcome any feedback or questions on the report itself.
