### ISSUE TITLE
support runner args for local:docker

### ISSUE THREAD

**Issue by GlenDC** [testground/testground#1505]
## Description

Today, one can already define in the `manifest.toml` file of a testplan builder-args for a `docker:generic` builder.

It is however not yet possible to define args that can be given to the `local:docker` runner when running an already built image.
As a result it is currently only possible to add dynamic features to a Generic dockerfile using build args, rather than also
supporting args that can be injected without having to rebuilt the image.

If we can support this it can make our`docker:generic` images a lot more flexible.

**Comment by GlenDC** [comment]
Speciically this would mean we expose the ability to be able to define environment variables:

https://docs.docker.com/engine/reference/run/#env-environment-variables

**Comment by laurentsenta** [comment]
Note that testground already provides a way to pass runtime parameters to tests:
https://docs.testground.ai/writing-test-plans/paramaters-and-testcases

**Comment by GlenDC** [comment]
Yes. But these are parameters specific to the SDK.
Regardless of the browser efforts I do think it makes sense to be able to define also environment variables for a runner,
as it fits IMHO into the `docker:generic` approach, where you have no clue why it might be useful.

**Comment by laurentsenta** [comment]
They solve the same problem: as a developer, I want to pass parameters to my test instance at runtime.
They are both using the same mechanic (env variables).
One is going through the testground SDK, and the other is not.

Note that the concept of builder doesn't really exist when you reach the runtime part: you have a binary usually running in a container, and it tries to access "something" configured by the user.

I'm sort of neutral as to which we use, and we'll merge #1386
I think it's better to stick to testground's SDK when you can:

- It makes sense to have the SDK help with these (in some runtimes, like browser, ENV variables are not easy to work with).
- Even if you use the `docker:generic` builder, you need a Testground SDK to do anything more involved than a helloworld. I would not optimize for the case "someone tries to run code without the SDK", we're not building a container execution platform.
- I would rather have one way to do something that works everywhere, rather than multiple approaches.

**Comment by GlenDC** [comment]
Fair enough. You persuaded me completely. I agree with you here 100%. Going to close it.
Also going to close the open PR.
