### ISSUE TITLE
Testing testground/testground-infra#78

### ISSUE THREAD

**Issue by galargh** [testground/testground#1518]
I'm going to use this issue to document the testing of https://github.com/testground/infra/pull/78 performed on 2022-11-09. If you want to click around the dashboard, you can go to http://a106f6db4c1fa4eadb9c07cc0600af50-316085603.eu-west-3.elb.amazonaws.com/tasks. I'm letting it run for a while to see if the storage persists as expected.

I will be hiding my original feedback comments as soon as they're resolved.

**Comment by galargh** [comment]
1. How do I delete a cluster if .cluster/*.cs file was never created? Repro scenario, kick off testground_install and kill it soon after. The cluster creation will kick off but the cluster file will not be created. How do I delete that cluster?

**Comment by galargh** [comment]
2. Is there any way to make the install script resume after machine goes to sleep? If not, could we add an explicit reminder for people not to let it happen.

**Comment by galargh** [comment]
3. Why is monitoring not enabled by default?

**Comment by galargh** [comment]
3. Why is monitoring not enabled by default?

**Comment by galargh** [comment]
4. `bash: ./monitoring.sh: /bin/bash: bad interpreter: Permission denied`

**Comment by galargh** [comment]
5. We use default prometheus operator now, right? Could you please go through the list of deviations from defaults listed in https://github.com/testground/infra/blob/master/k8s/prometheus-operator/values.yaml#L2 and argument why we don't need it anymore?

**Comment by galargh** [comment]
6. We don't do any grafana dashboard setup that we used to do in https://github.com/testground/infra/tree/master/k8s/testground-infra. I wouldn't say that monitoring is complete without it.

**Comment by galargh** [comment]
7. When I run `testground run single --plan=splitbrain --testcase=accept --builder=docker:go --runner=cluster:k8s --instances=200`, I found this in the journal:
```
Events
=================
obj<tg-splitbrain-cdlmd5126unciq56l7g0-single-7> type<ADDED> reason<FailedMount> message<Unable to attach or mount volumes: unmounted volumes=[efs-shared kube-api-access-w8z94], unattached volumes=[efs-shared kube-api-access-w8z94]: error processing PVC default/efs: failed to fetch PVC from API server: persistentvolumeclaims "efs" is forbidden: User "system:node:ip-192-168-56-232.eu-west-3.compute.internal" cannot get resource "persistentvolumeclaims" in API group "" in the namespace "default": no relationship found between node 'ip-192-168-56-232.eu-west-3.compute.internal' and this object> type<Warning> count<1> lastTimestamp<2022-11-09 08:39:10 +0000 UTC>
```

**Comment by galargh** [comment]
8. Clicking `dashboard` link in the dashboards leads to a page that says `Cannot get measurements`. Why is that?

**Comment by galargh** [comment]
9. How do we control debug logging? Is it a cluster setting? Or could we make info the default but allow to set debug per test plan?

**Comment by galargh** [comment]
10. When I scheduled `testground run single --plan=benchmarks --testcase=storm --builder=docker:go --runner=cluster:k8s --instances=250` twice it seems like they deadlocked. Each of them got to a place where no more pods could be scheduled so they all timed out after 15 minutes. Is that expected?

**Comment by brdji** [comment]
> 9. How do we control debug logging? Is it a cluster setting? Or could we make info the default but allow to set debug per test plan?

I believe it is a cluster setting, controlled by an env var `LOG_LEVEL`. We did not change any behavior of the logging, so I believe the default is set by the config (see [cluster_k8s code](https://github.com/testground/testground/blob/9c13f3bbe956c3cc29591db4b8b3c63b6fa1f6dc/pkg/runner/cluster_k8s.go#L307) ).

**Comment by AbominableSnowman730** [comment]
> 1. How do I delete a cluster if .cluster/*.cs file was never created? Repro scenario, kick off testground_install and kill it soon after. The cluster creation will kick off but the cluster file will not be created. How do I delete that cluster?

It's mentioned in the README:

>  If the file is removed or changed in any way, the uninstall script will output error message(s) stating this. In that case, the .cs file needs to be populated again, or the resources will have to be removed manually from your AWS account. 

If it's stopped shortly after it's creation, I believe that the `eksctl` command can be used as well (since no other resources were created before it):

`eksctl delete cluster --name $CLUSTER_NAME --region $CLUSTER_REGION`

If it makes sense, we can add the command to the README as well.

**Comment by AbominableSnowman730** [comment]
> 2. Is there any way to make the install script resume after machine goes to sleep? If not, could we add an explicit reminder for people not to let it happen.

No way to resume after a machine goes to sleep. A reminder will be added.

**Comment by AbominableSnowman730** [comment]
> 3. Why is monitoring not enabled by default?

We reasoned not to enable it by default, so that cluster resources aren't taken by something not requested explicitly. In that sense, it may make more sense to explicitly request monitoring for the cluster, if desired. 
Not sure what the majority of users will require of it. If you believe it will be something that most of them will need, we'll add it as a default option.

**Comment by AbominableSnowman730** [comment]
> 8. Clicking `dashboard` link in the dashboards leads to a page that says `Cannot get measurements`. Why is that?

Should be an InfluxDB issue. Looking into it.

**Comment by galargh** [comment]
> > 3. Why is monitoring not enabled by default?
> 
> We reasoned not to enable it by default, so that cluster resources aren't taken by something not requested explicitly. In that sense, it may make more sense to explicitly request monitoring for the cluster, if desired. Not sure what the majority of users will require of it. If you believe it will be something that most of them will need, we'll add it as a default option.

If you could enable it by default, that'd be great. Thank you 🙇

**Comment by galargh** [comment]
> > 1. How do I delete a cluster if .cluster/*.cs file was never created? Repro scenario, kick off testground_install and kill it soon after. The cluster creation will kick off but the cluster file will not be created. How do I delete that cluster?
> 
> It's mentioned in the README:
> 
> > If the file is removed or changed in any way, the uninstall script will output error message(s) stating this. In that case, the .cs file needs to be populated again, or the resources will have to be removed manually from your AWS account.
> 
> If it's stopped shortly after it's creation, I believe that the `eksctl` command can be used as well (since no other resources were created before it):
> 
> `eksctl delete cluster --name $CLUSTER_NAME --region $CLUSTER_REGION`
> 
> If it makes sense, we can add the command to the README as well.

This is fine, thanks for the explanation :)

**Comment by laurentsenta** [comment]
I'm going through the tests that check on a small cluster I deployed myself and on the cluster that @galargh deployed that uses the default config.

The `traffic-blocked` example doesn't pass on the cluster (it does on a local docker daemon).

These are what I have so far:

```sh
# ok
testground run single --plan=testground/network --testcase=ping-pong --builder=docker:go --runner=cluster:k8s --instances=2 --wait

# ok
testground run single --plan=testground/network --testcase=traffic-allowed --builder=docker:go --runner=cluster:k8s --instances=1 --wait

# failed
testground run single --plan=testground/network --testcase=traffic-blocked --builder=docker:go --runner=cluster:k8s --instances=1 --wait
```

**Comment by laurentsenta** [comment]
Also @galargh could you confirm, 7 days ago you submitted some tasks to this cluster:
http://a106f6db4c1fa4eadb9c07cc0600af50-316085603.eu-west-3.elb.amazonaws.com/tasks

I can only see my tasks (submitted yesterday), which seems to indicate the storage issue is not solved.

**Comment by brdji** [comment]
> Also @galargh could you confirm, 7 days ago you submitted some tasks to this cluster: http://a106f6db4c1fa4eadb9c07cc0600af50-316085603.eu-west-3.elb.amazonaws.com/tasks
> 
> I can only see my tasks (submitted yesterday), which seems to indicate the storage issue is not solved.

We have been able to reproduce this on one of our clusters, and are working to fix this.

**Comment by brdji** [comment]
> 8. Clicking `dashboard` link in the dashboards leads to a page that says `Cannot get measurements`. Why is that?

We have added & tested the InfluxDB integration. This fixes the "Cannot get measurements" issue; however, we have noticed that even on the `master` branch, when running tests, clicking the dashboard link returns the message "No measurements for this test plan". The only test that seems to return results is the 'benchmarks' test plan; however, for some reason, the dashboard attempts to access the `benchmark` plan (typo: note the missing 's'), and the link does not return any measurements. 

Both seem to be preexisting issues not caused by our EKS work. Please advise on how to continue.

**Comment by brdji** [comment]
> I'm running tests on a small cluster I deployed myself and on the cluster that @galargh deployed which uses the default config.
> 
> The `traffic-blocked` example doesn't pass on the cluster (it does on a local docker daemon).
> ...

The cause of this seems to lie in how Testground handles the `RoutingPolicy` settings.

1. We are unsure what the RoutingPolicy is supposed to prevent/allow. `RoutingPolicy.DenyAll` is used in the following tests:
- `traffic-blocked`: Here it is used to prevent a node from accessing an IPFS link (egress)
- `ping-pong`: Here we are not sure what it is used for. The test actually tests bidirectional (both egress and ingress) communication, so the routing policy does not seem to belong here. 

If the `DenyAll` policy is supposed to prevent both directions of traffic, shouldn't it also prevent the `ping-pong` test from passing?

2. The routing policy is handled in a [very unwieldy way](https://github.com/testground/testground/blob/97849cb74c605284b17765ddb971bf14792acfbd/pkg/sidecar/route.go#L68): if the policy is `DenyAll`, then all routes for a link are deleted. If the 
policy is `AllowAll`, then all routes are restored. The recommended way is to use [k8s native policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/). This would require some code changes, as the `k8s_network.go` (the file in charge of configuring the network) does not have access to the pods: we would have to allow the function some access to the pods, so that it could attach/remove the native policies.

Let me know if what I wrote makes sense!

**Comment by galargh** [comment]
> Also @galargh could you confirm, 7 days ago you submitted some tasks to this cluster: http://a106f6db4c1fa4eadb9c07cc0600af50-316085603.eu-west-3.elb.amazonaws.com/tasks
> 
> I can only see my tasks (submitted yesterday), which seems to indicate the storage issue is not solved.

Yes, they are gone. I see the team is on it: https://github.com/testground/testground/issues/1518#issuecomment-1319872917

**Comment by laurentsenta** [comment]
It does, thanks for the clarification, I'm fine not having this for iteration 1 of the EKS cluster.

> We have added & tested the InfluxDB integration. This fixes the "Cannot get measurements" issue; ...
> 
> Both seem to be preexisting issues not caused by our EKS work. Please advise on how to continue.

Thanks for adding InfluxDB, matching the previous cluster's state is fine for me.

**Comment by galargh** [comment]
> If the `DenyAll` policy is supposed to prevent both directions of traffic, shouldn't it also prevent the `ping-pong` test from passing?
> 
> 2. The routing policy is handled in a [very unwieldy way](https://github.com/testground/testground/blob/97849cb74c605284b17765ddb971bf14792acfbd/pkg/sidecar/route.go#L68): if the policy is `DenyAll`, then all routes for a link are deleted. If the
>    policy is `AllowAll`, then all routes are restored. The recommended way is to use [k8s native policies](https://kubernetes.io/docs/concepts/services-networking/network-policies/). This would require some code changes, as the `k8s_network.go` (the file in charge of configuring the network) does not have access to the pods: we would have to allow the function some access to the pods, so that it could attach/remove the native policies.
> 
> Let me know if what I wrote makes sense!

I don't really get it. Could you expand on what's "unwieldy" about it? Do you suggest handling it differently for docker and k8s runners? Finally, how does the current implementation relate to the results Laurent has observed?

**Comment by galargh** [comment]
I'm going to close this issue now. The main thing we'd like to see implemented is tracked by https://github.com/testground/testground/issues/1499#issuecomment-1320031708
