### ISSUE TITLE
Stalled test (likely network failure)

### ISSUE THREAD

**Issue by MarcoPolo** [testground/testground#1542]
#### Version information:

commit: https://github.com/testground/testground/commit/8629aa281a02bf6a193573a8e0e3959307aadf1d

MacOS M1
#### Description:

Output of test: https://gist.githubusercontent.com/MarcoPolo/f4a152873f8059a88b566d775497adb4/raw/b46e89dfcd40defe418454d8e3fc95a74804aee8/gistfile1.txt

If a container exits with a non-zero status code we should terminate the test.

**Comment by laurentsenta** [comment]
@MarcoPolo I don't have full logs, but I think what you see here is the rust test stalling ([We've seen this happen](https://github.com/libp2p/test-plans/pull/41#issuecomment-1256025245) in the libp2p/test-plan repos before).

So the go test completes, the rust test stalls, and there is probably a 60 minutes timeout by default in your test: https://github.com/libp2p/test-plans/blob/f8250cc3786ab1f9da2d1f999cbda22ed4943521/.github/actions/setup-testground/action.yml#L69

You could drop the timeout to 5 minutes in the testground conf, it won't be a big deal since we're not building with Testground (or disable the daemon in `testground-setup`).

> If a container exits with a non-zero status code we should terminate the test.

If ALL containers exit we terminate the test. Testground waits for the whole test to complete before gathering logs, outputs, metrics, and outcomes.

I'll update the description to emphasis the need to be more explicit about outputs.

## A note on the test itself:

- I tried running the test with only rust: https://github.com/laurentsenta/test-plans/actions/runs/3695981611#summary-10092695972 (passed)
- Only go: https://github.com/laurentsenta/test-plans/actions/runs/3696122500 (passed)
- Then all of them: https://github.com/laurentsenta/test-plans/actions/runs/3697441875

```
"rust-v0.50.0_x_go-v0.22.0(tcp,_noise,yamux)",ced154vo4a4bpm1mo1s0,failure,
"rust-v0.50.0_x_go-v0.23.4(tcp,_noise,yamux)",ced17ofo4a4bpm1mo1u0,failure,
```

- I also tried running twice all the go tests, in case that was an issue with the number of tests, it passed as well: https://github.com/laurentsenta/test-plans/actions/runs/3696390392

As I write this (I re-run all the tests just in case), It seems that the error happened with rust-v0.50.0 x go both times,

**Comment by laurentsenta** [comment]
Actually, I created https://github.com/testground/testground/issues/1551 as a follow-up, re-purposing your issue seems rude.

I'm going to close this one, please feel free to re-open it if fixing the timeout doesn't fix the error.

**Comment by MarcoPolo** [comment]
> As I write this (I re-run all the tests just in case), It seems that the error happened with rust- x go both times,

https://github.com/libp2p/test-plans/actions/runs/3798668092

Fails in a rust x rust test.
