### ISSUE TITLE
will the testground support runners  in  own test k8s cluster ..

### ISSUE THREAD

**Issue by linlin1988** [testground/testground#1588]
hi dear tg teams

i have a request 
is there any plan that testground will support the "customize k8s cluster " for runner ?

i mean , i have a own k8s cluster, deploy myself in my test , single server or multi server .

maybe can connect to my k8s cluster by adding kubeconfig / apiserver endpoint such as "https://myserver:6443" to in the   env.toml  ? 

so than i can start my testplan instance in my own cluster , but not the aws cluster

**Comment by linlin1988** [comment]
waiting the reply , thank you so much

**Comment by Bidon15** [comment]
Hey @linlin1988, 
Thanks for the question! 

Indeed, we want testground to be hosted on whatever k8s env / cp user chooses to operate. The work is going to be kick-started in the nearest future to make it cloud provider agnostic. 

For now, you can only operate on an AWS real due to the inherit design choices made in testground/infra repo.

**Comment by Bidon15** [comment]
We will inform the community soon on our next steps as soon as we have a shaped roadmap and implementation timelines / features drafted out

**Comment by linlin1988** [comment]
hi @Bidon15 

thank you so much .   its a great feature .

**Comment by linlin1988** [comment]
very good news
