### ISSUE TITLE
Support for Rust test plans

### ISSUE THREAD

**Issue by vmx** [testground/testground#621]
## Description

It would be great to have support for Rust test plans in order to test PRs that might break things in unexpected way.

One example is https://github.com/libp2p/rust-libp2p/pull/1472#issuecomment-593498266, where a > 1.5 years old fork of a core dependency gets replaced by the upstream crate. 

## What defines this endeavour to be complete?

- [X] I can run that PR on a live system to see if things break in unexpected ways

**Comment by nonsense** [comment]
@vmx it would be helpful if you elaborate on what test plan you would like to see in order to confirm that the PRs is not `breaking things in an unexpected way`, just so that we have an idea of what parts of the Testground `sdk` would need a Rust implementation.

It might be the case that there is a low-hanging fruit we could reach that gives you enough confidence that the PR works, before we have a full-fledge implementation of the `sdk` in Rust - something that is not a priority right now AFAIK. We've spoken about `js` version of the Testground `sdk`, but I don't think we've considered a Rust one :)

**Comment by vmx** [comment]
I don't know enough about libp2p. But something similar to https://github.com/libp2p/rust-libp2p/pull/1472#issuecomment-593498266: spinning up 25 nodes, run some basic operations (I'd guess there's some basic tests you'd normally run) and check that there are no additional errors compared to a run with that PR applied.

**Comment by laurentsenta** [comment]
We do support rust now (credit to @mxinden for the rust SDK)

example: https://github.com/testground/testground/tree/master/plans/example-rust
SDK: https://github.com/testground/sdk-rust

**Comment by mxinden** [comment]
> (credit to @mxinden for the rust SDK)

:pray: and @SionoiS and @ackintosh.
