### ISSUE TITLE
prometheus crashes with OOM

### ISSUE THREAD

**Issue by nonsense** [testground/testground#851]
We need to understand what's wrong with Prometheus, because it keeps on crashing, even when I give it 8GB of RAM.

@coryschwartz do you know what are the requirements for it, and whether we need to reduce the retention rate?

```
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    OOMKilled
      Message:   aded" segment=18 maxSegment=27
level=info ts=2020-04-15T13:44:41.426Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=19 maxSegment=27
level=info ts=2020-04-15T13:44:41.636Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=20 maxSegment=27
level=info ts=2020-04-15T13:44:41.937Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=21 maxSegment=27
level=info ts=2020-04-15T13:44:42.203Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=22 maxSegment=27
level=info ts=2020-04-15T13:44:42.328Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=23 maxSegment=27
level=info ts=2020-04-15T13:44:45.715Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=24 maxSegment=27
level=info ts=2020-04-15T13:44:47.791Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=25 maxSegment=27
level=info ts=2020-04-15T13:44:47.859Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=26 maxSegment=27
level=info ts=2020-04-15T13:44:47.859Z caller=head.go:632 component=tsdb msg="WAL segment loaded" segment=27 maxSegment=27
level=info ts=2020-04-15T13:44:51.162Z caller=main.go:663 fs_type=EXT4_SUPER_MAGIC
level=info ts=2020-04-15T13:44:51.162Z caller=main.go:664 msg="TSDB started"
level=info ts=2020-04-15T13:44:51.162Z caller=main.go:734 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2020-04-15T13:44:51.165Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-04-15T13:44:51.166Z caller=kubernetes.go:190 component="discovery manager scrape" discovery=k8s msg="Using pod service account via in-cluster config"
level=info ts=2020-04-15T13:44:51.186Z caller=main.go:762 msg="Completed loading of configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2020-04-15T13:44:51.186Z caller=main.go:617 msg="Server is ready to receive web requests."

      Exit Code:    137
      Started:      Wed, 15 Apr 2020 15:44:09 +0200
      Finished:     Wed, 15 Apr 2020 15:45:55 +0200
    Ready:          False
    Restart Count:  10
    Limits:
      cpu:     4
      memory:  8000Mi
```

**Comment by nonsense** [comment]
One of the reasons why `prometheus` might be crashing is due to queries from Grafana from some of the dashboards that show `pod` information. I've noticed that just opening the dashboards that show CPU/memory for pods after having run a testplan with 1000 instances, results in a crash.

---

The dashboards that show pod information are mostly unusable, specially when they automatically open the `default` namespace.

It would be useful to show pod information if we have a namespace for our infra pods, but as soon as these get merged with testplan pods, Grafana becomes non-responsive.

**Comment by coryschwartz** [comment]
Even running a small test over and over again results in the memory consumption for prometheus increasing. As soon as the memory reaches our limit (6000Mi) we OOM and crash. To make matters worse, after restarting, the data gets loaded again and OOMs again very quickly. The way to limit memory is different depending on the version of prometheus. Using the prometheus operator abstracts away some details and finding the right configuration to do what you expect is not obvious.



Prior to v1.6, the way to manage memory is by managing the number of "memory chunks", which are 1024-byte segments. These chunks are stored to disk, but it is up to the user about how to calculate the number of memory chunks, but these chunks don't represent the whole picture, additional memory is allocated for management and it is very hand-wavy. If running prometheus on its own, there is a commandline flag which guides this behavior `-storage.local.memory-chunks` and `-storage.local.max-chunks-to-persist`

on major revision 1 v1.6+ a new flag is added `-storage.local.target-heap-size` is introduced. With this feature, you can more easily predict the amount of memory prometheus will use. Brilliant.
https://github.com/prometheus/prometheus/pull/2527/files

Using prometheus-operator details such as this are abstracted away from the user. They have discussion here https://github.com/coreos/prometheus-operator/issues/203 and about setting flags in general https://github.com/coreos/prometheus-operator/issues/306. The result of the discussion is that you can't set flags, but you can request memory and the operator will decide for you how to configure the heap size.  it does this by simply multiplying the memory requested by 2/3 and calling setting this the heap size. You can see this here:
https://github.com/coreos/prometheus-operator/blob/master/pkg/prometheus/statefulset.go#L335

In other words, add this stanza to your yaml, and let the prometheus-operator figure it out.
```
(in PrometheusSpec)
    resources:
      requests:
         memory: XXXXMi
```

If you followed that link you might notice that on major release 2+ this will do nothing for you. In v2 a new tsdb is used which makes use of a persistent write-ahead-log. There is no longer a concept for "memory chunks". The write-ahead log can be replayed if the system crashes, the WAL keeps an active page of a specific size and flushes to disk when the page is full. Wal Pages are only "in memory" so long as they are in the system filesystem cache. From a memory perspective, the last block is kept in memory, but queries could bring in additional blocks.

It turns out, though, that large queries may fill the memory. As you might guess, the prometheus engine uses this number when evaluating queries. This is guided by the command-line flag `-query.max-samples` and `-query.max-concurrency`. However, in our case, this was insufficient to keep the memory in check. You can adjust this value with `storage.tsdb.max-block-duration`. When using the operator, this can be set by disabling compaction. 

Lets see if these help and tune farther: https://github.com/testground/infra/pull/36

**Comment by nonsense** [comment]
Closed in favour of https://github.com/testground/testground/issues/911
