### ISSUE TITLE
integration tests for cluster:k8s

### ISSUE THREAD

**Issue by raulk** [testground/testground#879]
PLEASE!

What we discussed off-band:

- [ ] Migrating to CircleCI because it has native Kubernetes support.
- [ ] Omit anything that requires a special k8s network setup, so that we can use a barebones setup. Sidecar should be tested elsewhere.
- [ ] We will probably need to create some kind of test harness so that in the future we can write such integration tests easily (calling the runner directly?).

@nonsense @coryschwartz Let's all think about this and share ideas before engaging in hardcore implementation.

---

Related: https://github.com/testground/testground/issues/449

**Comment by coryschwartz** [comment]
Kubernetes support on CircleCI, I am confident we can test most/nearly all components of the system this way, but I am less confident about the sidecar unless we can figure out CNI support.

**Comment by coryschwartz** [comment]
Maybe just add an option to the k8s runner to disable TestSideCar for now, integration tests for everything, and perhaps mock api tests for the sidecar. What are your thoughts?

**Comment by coryschwartz** [comment]
@nonsense 

I did some experiments getting testground to work on k3s. I never got it totally working. I had notes going while I was doing the experiment, so here are my rambling, un-filtered notes:

the tl;dr is that I to run k3s in CI we  need to remove restricted sysctls and keep the memory and CPU resources fairly minimal.

It might also be a good idea to offer custom image registries, but overall it seems possible to get a minimal kubernetes cluster setup this way with enough to run a few plans.

I see the purpose for this primarily to testing the k8s runner and the sidecar, and I think with some changes we can make this work. 



----- Notes: 

install k3s curl -sfL https://get.k3s.io | sh -

git clone https://github.com/testground/infra

Must run as root, due to the permissions setup on /etc/rancher/k3s
# ls -l /etc/rancher/k3s
total 4
-rw------- 1 root root 1052 Apr 23 01:24 k3s.yaml


install a minimal set of kubernetes components.

First, set the node to have the right label so the sidecar will be scheduled.

kubectl label nodes $(hostname) testground.nodetype=plan

kubectl apply -f .kops-weave/weave.yml
kubectl apply -f ./kops-weave/genie-plugin.yaml
kubectl apply -f ./kops-weave/dummy.yml
kubectl apply -f ./sidecar.yaml


weave can't be installed due to insufficient CPU.
I switched the CPU to 1000m and it started, and got to the stage "wait-for-flannel"

I went ahead and installed flannel, with no configuration. `kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml` but this needs to be configured to work, and weave did not kick in after installing it.


The sidecar is waiting for redis, lets install that:

curl https://get.helm.sh/helm-v3.2.0-linux-amd64.tar.gz | sudo tar -C /usr/local/bin -xzvf - linux-amd64/helm --strip-components 1
sudo chmod +x /usr/local/bin/helm

helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm repo  update
helm install testground-infra-redis bitnami/redis
Error: Kubernetes cluster unreachable

weird. https://rancher.com/docs/k3s/latest/en/helm/ says it supports helm.

I do have the right version.
k3s --version
k3s version v1.17.4+k3s1 (3eee8ac3)


ah. Of course. 

https://github.com/rancher/k3s/issues/1126

and oh well hell, authentication is enabled on redis. Well okay, lets install the whole thing.

helm install prometheus-operator
helm install testground infra, as per usual

this doesn't work, there isn't enough memory on the CI machine to do this.


I got redis running with this pared down values:

```
---
cluster:
  enabled: false
usePassword: false
master:
  persistence:
    enabled: false
  extraFlags:
    - "--maxclients 131072"
  resources:
    requests:
      memory: 500Mi
      cpu: 500m
    limits:
      memory: 500Mi
      cpu: 500m
```

I get an error with somaxcon. Maybe it's not possible to whitelist "safe" not sure.
https://github.com/rancher/k3s/blob/master/vendor/k8s.io/kubernetes/pkg/security/podsecuritypolicy/sysctl/mustmatchpatterns.go#L32


finally, sidecar and redis are both running.

Tried to run testground without uploading the image. Maybe k3s can find the image from local docker images?

Turns out, testground daemon doesn't like k8s config being in another location, or doesn't use the KUBECONFIG environment variable. I copied the config from /etc/k3s into ~/.kube/config and it panics about something. this comes after the build, during the runner.

```
Apr 23 06:54:30.069162  INFO    request handled {"ruid": "cffeb52a", "command": "build"}
Apr 23 06:54:30.070109  INFO    performing healthcheck on runner        {"req_id": "dc3e17f9"}
Apr 23 06:54:30.122686  INFO    healthcheck: ok {"req_id": "dc3e17f9"}
2020/04/23 06:54:30 http: panic serving 127.0.0.1:42252: cannot parse '': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
goroutine 9 [running]:
net/http.(*conn).serve.func1(0xc000298640)
        /root/go/src/net/http/server.go:1772 +0x139
panic(0x178dc40, 0xc0007be770)
        /root/go/src/runtime/panic.go:975 +0x3e3
k8s.io/apimachinery/pkg/api/resource.MustParse(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/k8s.io/apimachinery@v0.17.0/pkg/api/resource/quantity.go:127 +0x1c8
github.com/testground/testground/pkg/runner.(*ClusterK8sRunner).Run(0x2c2cdc0, 0x1d5d9a0, 0xc00024e810, 0xc0003b5700, 0xc00024e960, 0x0, 0x0, 0x0)
        /home/circleci/project/pkg/runner/cluster_k8s.go:144 +0x221
github.com/testground/testground/pkg/engine.(*Engine).DoRun(0xc000104600, 0x1d5d9a0, 0xc00024e810, 0xc0003030e0, 0xc00024e960, 0x0, 0x0, 0xc000203970)
        /home/circleci/project/pkg/engine/engine.go:351 +0xcaa
github.com/testground/testground/pkg/daemon.(*Daemon).runHandler.func1(0x1d58760, 0xc000510380, 0xc0003b4100)
        /home/circleci/project/pkg/daemon/run.go:29 +0x4c4
net/http.HandlerFunc.ServeHTTP(0xc000126860, 0x1d58760, 0xc000510380, 0xc0003b4100)
        /root/go/src/net/http/server.go:2012 +0x44
github.com/testground/testground/pkg/daemon.New.func1.1(0x1d58760, 0xc000510380, 0xc0003b4100)
        /home/circleci/project/pkg/daemon/daemon.go:44 +0x14f
net/http.HandlerFunc.ServeHTTP(0xc00000f740, 0x1d58760, 0xc000510380, 0xc0003b4100)
        /root/go/src/net/http/server.go:2012 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0005c4000, 0x1d58760, 0xc000510380, 0xc000139e00)
        /root/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
net/http.serverHandler.ServeHTTP(0xc0005d2000, 0x1d58760, 0xc000510380, 0xc000139e00)
        /root/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc000298640, 0x1d5d8e0, 0xc0001047c0)
        /root/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
        /root/go/src/net/http/server.go:2933 +0x35c
```


so it cannot parse podResourceCPU

I just manually set this in the code and hey hey! it schedules!

It doesn't actually execute, though because it wants persistent volumes.

```
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  persistentvolumeclaim "efs" not found
  Warning  FailedScheduling  <unknown>  default-scheduler  persistentvolumeclaim "efs" not found

```

I tried one last time, this time removing the persistent volume from the kubernetes runner spec.

I had to remove the forbidden sysctl net.cor.somaxconn as well.

ErrImagePull, lets try uploading to docker

I tried using this to upload images to docker hub..

```
./testground run single --builder docker:go --runner
 cluster:k8s --instances 2 --run-cfg keey_service=true --build-cfg registry_type=dockerhub --build-cfg push_registry=true netw
ork:ping-pong 
```

There is an error here, because the image saved has the build ID as its tag, but there is an error that tag "latest"  is not found

**Comment by nonsense** [comment]
@coryschwartz great stuff! I see you almost got it, so this is indeed looking very good.

1. Resources - we have been very generous with resources for pods, I can totally see how this is a problem on CI, we should see how to configure them separately on CI and on our prod environment.

2. `cannot parse '': quantities must match the regular expression` - I believe this is due to missing / misconfigured `.env.toml` file. We expect the defaults to be specified there.

3. Dockerhub - I am not surprised we might have broken this, nobody has really used it for months. I am wondering if there is a way to use another registry for the cluster in CircleCI, but Dockerhub should be fairly easy to fix for a POC of the integration tests.

4. `testground daemon doesn't like k8s config` - we might need to refactor that.

5. `weave got to the stage "wait-for-flannel"` - `weave` is waiting for the `flannel.1` interface to appear, this might be configured differently.

---

Overall great progress, I think we can make this work.

**Comment by coryschwartz** [comment]
Sorry there haven't been regular updates here, I have been constantly putting this on the back burner or thinking I will get to this in the second part of the day. 

In addition to the work I outlined above with k3s, I have also explored using 'kind'. Both of these projects have a similar idea -- to run kubernetes on basic docker nodes.

Kind has a feature that I didn't notice on k3s -- the ability to import local docker images into the images available to kubernetes. This would kill the need for downloading the sidecar from a docker hub, and actually might be the motivating factor for selecting one over the other. We are, after all, going to be using this to test the sidecar. It would be best if the freshly-built image.

I am trying to get multiple-networks available. 

Now that we are focusing on "hardening" I expect this can be more front and center.

**Comment by coryschwartz** [comment]
With reagrad to multiple networks on kind, the way to do this is just attaching a second network to kind worker nodes using `docker network attach` -- this enables the kind kubernetes nodes to see multiple network interfaces, and then the networking can configure these.

On the other hand, we need to be careful about testing the right surfaces. Our goal is not to test weave, but to test the k8s runner and the sidecar. With that in mind, it may be in fact a better test to swap out the sidecar networking with a mock network so that most of the sidecar can be tested. The k8s runner can be tested simply by the virtue of using k8s endpoints of any kind.

**Comment by coryschwartz** [comment]
Yesterday we merged https://github.com/testground/testground/pull/993  which is sufficient to test the runner, although not the sidecar. It really is just a "barebones" k8s to test the runner.

Decided to use `kind` rather than `k3s` because it permits you to load images from local docker.

This does not test the sidecar or the networking!

As @nonsense and I have discussed, kind and k3s use containerd, so the sidecar cannot manage the networking (it requires direct docker socket access) Further work is ongoing to do sidecar testing.

I think this can be closed and we will continue to work on the sidecar testing.

**Comment by nonsense** [comment]
Some work in progress work on integration of sidecar with containerd is happening at: https://github.com/testground/testground/pull/1013

**Comment by nonsense** [comment]
Just an update on what was discussed off-band over the last 1-2 days:

> With reagrad to multiple networks on kind, the way to do this is just attaching a second network to kind worker nodes using `docker network` attach -- this enables the kind kubernetes nodes to see multiple network interfaces, and then the networking can configure these.

We figured this doesn't work because `kind` is using `containerd` and not `docker`.

> On the other hand, we need to be careful about testing the right surfaces. Our goal is not to test weave, but to test the k8s runner and the sidecar. With that in mind, it may be in fact a better test to swap out the sidecar networking with a mock network so that most of the sidecar can be tested. The k8s runner can be tested simply by the virtue of using k8s endpoints of any kind.

1. We decided that Mock network is nice for the Unit tests for the sidecar, but doesn't really help us with the `sidecar`, and any test plan that need the sidecar. We cannot really do a dummy network reactor, because we still need to listen for events on `containerd`, etc.

2. I think with respect to testing cluster:k8s testplans that need the sidecar, the majority of the work is actually supporting `containerd` in the sidecar, so we might as well just install `weave` and run a full end-to-end integration. No need for a mock network there.

cc @coryschwartz
