### ISSUE TITLE
Expose Redis Client in sync.Client

### ISSUE THREAD

**Issue by lthibault** [testground/testground#963]
## Description

The `sync` package in the Go SDK does a great job of providing useful abstractions like `Barrier`, which simplify many test plans.  In the spirit of the 80/20 rule, it seems like the set of planned synchronization primitives (lock, semaphore, etc) will cover 80% of use cases.

I suspect, however, that the remaining 20% will require more fine-grained synchronization logic that is tied to the specifics of the application being tested.  From the point of view of the test developer, it is desirable to have direct access to the Redis client in such cases.

Personally, I am in the midst of such a situation.  I am testing an application written with libp2p that uses a custom discovery mechanism.  In order to ensure this custom logic is robust, I need to test for a variety of discovery scenarious, which in turn means I need fine-grained control over which peers each instance detects at startup.  While this is relatively straightforward with Redis primitives, it quickly becomes tedious and convoluted if I need to abuse `Barrier` and `PubSub`.

For these reasons, I propose adding the following method to `sync.Client`:

```
func (c Client) RedisClient() *redis.Client {
    return c.rclient
}
```

I believe the benefit of closing the "20% gap" far outweighs any eventual risk of this method being misused.  I'm happy to submit a PR for this if you kind folks approve :)

Thoughts?

### TODO

- [x] Add `sync.Client.RedisClient` method

**Comment by raulk** [comment]
Interesting! I think exposing the internals at this stage could be a good idea, so that folks can experiment by building their own synchronisation primitives, which they can later contribute to the toolbox.

Just to make sure I've understood the use case, would you mind describing it in detail?

Thanks!

**Comment by nonsense** [comment]
I'd be careful about exposing Redis through the sync API. We are planning on moving to shared-cluster environments, at some point also running concurrently a number of test plans. We wouldn't want them to interfere with each other.

Ultimately we might end up adding another layer of abstraction - literally extracting a shared sync service that testplans, so that we are sure that they don't mess up directly with Redis.

I don't see a reason to change the sync API - testplans currently have all the information required to instantiate their own Redis client - why not do just that?

**Comment by lthibault** [comment]
@raulk 

>I think exposing the internals at this stage could be a good idea, so that folks can experiment by building their own synchronisation primitives, which they can later contribute to the toolbox.

I hadn't thought of that, but good point!  I'll be sure to submit a PR if I come up with something repeatedly useful.

>Just to make sure I've understood the use case, would you mind describing it in detail?

Sure!

At a high level, peers are self-assembling into an [expander graph](https://en.wikipedia.org/wiki/Expander_graph).  To understand what I'm trying to do, it's helpful to start with an existing cluster in a steady state and work backwards to the discovery/bootstrapping problem.

In the steady state, each peer wants to maintain a fixed number `k > 0` of connections to _random_ peers.  The value of `k` is fairly small; `k=8` by default.  The `k` connected peers are called _neighbors_.

The fact that these connections be random is crucial, so there are two protocols to ensure the graph maintains its stochastic properties.  The first is a steady-state protocol called "random eviction":  every few minutes, a peer will terminate its connection to a randomly-selected neighbor, and open a connection to a new, randomly-selected, neighbor.  The second is a bootstrap protocol called "random grafting", and works as follows.

When a peer first starts, it uses a discovery service to detect a small number of arbitrary bootstrap peers.  Importantly, it discovers `n < k` peers (usually just two or three), and these peers are **not** guaranteed to be random, so we have to do a bit of extra work!  Once the newly-started peer has connected to its initial `n` neighbors, it establishes its remaining `k-n` connections by randomly sampling the graph (the details of how it does this don't really matter, but it can be done via rendezvous or via a random-walk through the graph).

This brings us back to testing.  I need to ensure that for any initial state where the cluster forms a connected graph, a random connected graph eventually emerges.  As such, I want to provide a redis/sync.Client-backed discovery services that can deterministically build a number of edge-case topologies.  The simplest examples are

- A ring (all peers have exactly two neighbors)
- A chain (two peers have one neighbor and the rest have two neighbors)

but there are also some more exotic cases, involving topologies that are _initially_ partitioned, but end up fusing after some time.

This involves quite a bit of coordination with Redis, with heavy use of transactions and sets.

Hopefully this is reasonably clear?

@nonsense 

>I don't see a reason to change the sync API - testplans currently have all the information required to instantiate their own Redis client - why not do just that?

If users are going to resort to instantiating their own Redis clients, then we haven't avoided any footgun.  All we've done is encouraged extra boilerplate.

If we're handing over the footgun on our terms, we can at least ensure it comes with a warning and/or guidance (e.g. in the docstring).

>We are planning on moving to shared-cluster environments, at some point also running concurrently a number of test plans. We wouldn't want them to interfere with each other.

Alternatively, we could expose a _separate_ client using a different Redis DB, but that precludes responsible (e.g. read-only) use of entries created by `sync.Client`.  Risky things should at least be maximally useful, so I don't really like this solution.

Again, I think it's unavoidable that many (most?) users will eventually need low-level access to Redis because distributed applications are inherently bespoke/specialized.

In the spirit of "harm reduction", we should at least hand out clean needles and use the opportunity to teach good hygiene.

**Comment by lthibault** [comment]
@raulk I've just encountered (another) problem that is trivially solved with `SADD`/`SRANDMEMBER`, but quite convoluted using the barriers/pubsub/signals/etc in the `sync` package.

As such, I've gone ahead and implemented this, but taken care to include a warning in the docstring to address Anton's points.

I'm at your disposal to discuss, if needed 🙂.

**Comment by raulk** [comment]
Sorry for the slow response here. Thanks for describing your use case in detail, that's super helpful!

The way we usually implement topology formation is by using a topic where all nodes publish their presence, their addresses, etc. All other nodes subscribe to this topic to consume all their peer's configuration.

Then we have a topology constructor algorithm, that just takes a slice of all peers that are participating in the test (obtained by subscribing to that topic), and applies the calculated topology.

This is possible because sync service topics are ordered, so all peers are guaranteed to receive entries in the same order.

Therefore, if I am peer 3, and I'm using the ring topology, I connect to peers 2 and 4.

If the topology needs to vary, we assume that the topology function is a state machine that uses either topics or barriers to synchronise with specific peers, to enter the next stage of the topology.

**Comment by lthibault** [comment]
>Sorry for the slow response here.

No worries - lots going on! 🙂 

>The way we usually implement topology formation is by using a topic where all nodes publish their presence, their addresses, etc. All other nodes subscribe to this topic to consume all their peer's configuration.

This is essentially my current approach, but I like how you've partitioned the problem space.  It seems I should be able to avoid much of the tedium by separating out "topology construction" from "presence publication" (the latter being pretty much identical across tests).

I'll give this a whirl now, but I nevertheless feel it might be appropriate to expose the Redis client for the reasons I mentioned in my previous posts.  How do you feel about https://github.com/testground/sdk-go/pull/29?

>If the topology needs to vary, we assume that the topology function is a state machine that uses either topics or barriers to synchronise with specific peers, to enter the next stage of the topology.

Do you have any examples I could study?

Thanks again for your help!
