### ISSUE TITLE
 Integration tests for cluster:k8s runner: running, termination, collection.

### ISSUE THREAD

**Issue by Robmat05** [testground/testground#997]
Please see Epic description for details on creating test

From TG channel discussion posed by @nonsense 

i’ve been working on integration tests for cluster:k8s - got kind working with flannel and weave , but obviously this is not enough as we need sidecar to get events from containerd and not docker. so i’ve been looking into containerd and the api it provides so that we could potentially support it.
 https://github.com/testground/testground/issues/997 and https://github.com/testground/testground/issues/986

ultimately i think it makes sense to review how that could work not just for testing, but also to have an idea of what it would take to get rid of docker, as sentiment is that other runtimes are faster.

---

1) i imagine for the short term, we will either go down the road that @coryschwartz has done yesterday - kubernetes on CI host, or

2) `kind` + `containerd` + sidecar (`k8s-containerd` runner)

3) no sidecar for `cluster:k8s` tests, just very simple test plans, and all tests around the sidecar and plans that need it, go through the `local:docker` runner on CircleCI

i think there is value to us being able to run all test plans with both cluster:k8s and local:docker runners, hence we do 1 and 2.

---

UPDATE: After discussions in the team, we decided to go with option 3) for this sprint.

**Comment by coryschwartz** [comment]
Just to run termination and collection, containerd isn't required. 

What prevents that from working currently is that the collect pod can't be scheduled with the kubernetes node labeling.

We could configure kind to use two nodes, one "infra" and one "plan"... That is, if we can get a proper shared volume. Probably doable.


The other option is to change the labeling so nodes can be labeled twice. Yesterday @nonsense suggested this labeling that would allow nodes to have both labels

testground.nodetype.infra=true
testground.nodetype.plan=true

**Comment by nonsense** [comment]
@coryschwartz you're right, the way this issue is defined as well as https://github.com/testground/testground/issues/986 , we don't have to include the `sidecar` as part of the desired tests for v0.6

However it'd be nice to also cover the `sidecar` with integration tests, while we are at it. There is a lot of plumbing and configuration params that would be nice to cover - even though we are not testing the production `kops` setup, I think this will lead to higher quality code on the `sidecar` and on `infra`, as well as better safety net.

**Comment by nonsense** [comment]
@coryschwartz we had a chat about this with @raulk as well, and he also suggests that we don't try to cover `sidecar` as part of the `cluster:k8s` tests. We discussed that as you suggest, we can cover the `cluster:k8s` without the `sidecar` functionality, and make sure that if we want to test `sidecar` functionality, we can use the `local:docker` runner.

Therefore we really don't need the `containerd` support in the `sidecar` in order to use `kind`.

---

One outstanding question is, which tool do we want to use for the `cluster:k8s` tests - `kind` or `kubeadm` ? I am already familiar with `kind` and we've done work on adding support for it, so probably we can move ahead and use that, and address the issues you already listed. WDYT?
